export enum EPermission {
  USE_WRITE = "USE_WRITE",
  USE_READ = "USE_READ",
  USE_MOD = "USE_MOD",
  USE_CREATE = "USE_CREATE",
  USE_CHANGESETTINGS = "USE_CHANGESETTINGS",
  USE_DELETE = "USE_DELETE",
  USE_CREATOR = "USE_CREATOR"
}
